// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwicgOk5UvzSKwN6AO4r9LLH9ozycD6Q8',
    appId: '1:515674357675:web:73a10bddd87fd163f89cee',
    messagingSenderId: '515674357675',
    projectId: 'requisition-system-finale',
    authDomain: 'requisition-system-finale.firebaseapp.com',
    storageBucket: 'requisition-system-finale.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyrF5_LP3ISZaIiaPszeRKXyN7IbhyzoU',
    appId: '1:515674357675:android:99f82e129ec5f929f89cee',
    messagingSenderId: '515674357675',
    projectId: 'requisition-system-finale',
    storageBucket: 'requisition-system-finale.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxtlI6s1MOPs6PSrBqs07t4QluOTrcv3Y',
    appId: '1:515674357675:ios:176707041e4d21e1f89cee',
    messagingSenderId: '515674357675',
    projectId: 'requisition-system-finale',
    storageBucket: 'requisition-system-finale.appspot.com',
    iosBundleId: 'com.example.reqSysFinale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxtlI6s1MOPs6PSrBqs07t4QluOTrcv3Y',
    appId: '1:515674357675:ios:176707041e4d21e1f89cee',
    messagingSenderId: '515674357675',
    projectId: 'requisition-system-finale',
    storageBucket: 'requisition-system-finale.appspot.com',
    iosBundleId: 'com.example.reqSysFinale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwicgOk5UvzSKwN6AO4r9LLH9ozycD6Q8',
    appId: '1:515674357675:web:88a35f8a3d5bdff5f89cee',
    messagingSenderId: '515674357675',
    projectId: 'requisition-system-finale',
    authDomain: 'requisition-system-finale.firebaseapp.com',
    storageBucket: 'requisition-system-finale.appspot.com',
  );
}
